In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5])


In [6]:
new_arr = np.zeros(len(arr) * 4 - 3)
new_arr[::4] = arr
new_arr

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

In [8]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
matrix[[0, 1]] = matrix[[1, 0]]
matrix

array([[3, 4],
       [1, 2],
       [5, 6]])

In [24]:
arr = np.array([1, 5, 2, -3, -5, 6, 8, 3, 3, 5, 4, 1, -5, 0, 2, 3])
values, counts = np.unique(arr, return_counts=True)
print(values[counts.argmax()])

3


In [27]:
array = np.ones((16, 16))
summed_blocks = array.reshape(4, 4, 4, 4).sum(axis=(1, 3))
print(summed_blocks)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [43]:
matrix = np.array([[1, 55], [3, 2], [54, 6]])
matrix = np.array(matrix.flatten())
matrix.sort()
matrix

array([ 1,  2,  3,  6, 54, 55])

In [47]:
A = np.array([1.5, 3.6, 5.7, 5.0, -3.4, -5])
Z = np.where(A > 0, np.ceil(A), np.floor(A)).astype(int)
Z

array([ 2,  4,  6,  5, -4, -5])

In [53]:
A = np.array([1.5, 3.6, 5.7, 5.0, -3.4, -5])
B = np.array([1, 5, 5.0, -3.4, -5])
Z = np.intersect1d(A, B)
Z

array([-5. , -3.4,  5. ])

In [65]:
B = np.array([1, 0, 5, 5.0, 0, 0, 0, -3.4, -5, 0, 5, 6, 7, 0])
(np.where(B[:-1] == 0)[0] + 1).max()

np.int64(10)